/* 3º EXERCÍCIO DE BANCO DE DADOS */

CREATE DATABASE COMERCIO; /* CRIAÇÃO DO BANCO */ 

USE COMERCIO; /* CONECTANDO-SE AO BANCO */

/* CRIAÇÃO DE TABELAS */ 
CREATE TABLE CLIENTE (
		IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT, /* CHAVE PRIMÁRIA */ 
		NOME VARCHAR(30) NOT NULL, /* NOT NULL OBRIGA COM QUE O USUÁRIO ENTRE COM ALGUM DADO */
		CPF VARCHAR(15)UNIQUE,
		EMAIL VARCHAR(50) UNIQUE, /* O UNIQUE FAZ COM QUE O DADO NÃO SE REPITA NA TABELA, ENTÃO NÃO VAI EXISTIR O DADO IGUAL */
		SEXO ENUM( 'MASCULINO', 'FEMININO') NOT NULL /* ENUM DELIMITA QUAIS OPÇÕES ESTARÃO DISPONÍVEIS */ 
);

CREATE TABLE ENDERECO(
		IDENDERECO INT PRIMARY KEY AUTO_INCREMENT, 
		RUA VARCHAR(30) NOT NULL, 
		BAIRRO VARCHAR(30) NOT NULL, 
		CIDADE VARCHAR(30) NOT NULL, 
		ESTADDO CHAR(2) NOT NULL, 
		ID_CLIENTE INT UNIQUE,
		FOREIGN KEY(ID_CLIENTE) /* CHAVE ESTRANGEIRA */ 
		REFERENCES CLIENTE(IDCLIENTE) /* REFERENCIA A COLUNA */ 
);		

CREATE TABLE TELEFONE(
		IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
		NUMERO VARCHAR(13) NOT NULL,
		TIPOS ENUM('CELULAR','RESIDENCIAL','COMERCIAL') NOT NULL,
		ID_CLIENTE INT,
		FOREIGN KEY (ID_CLIENTE)
		REFERENCES CLIENTE(IDCLIENTE)
);

/* INSERINDO DADOS NA TABELA CLIENTE */ 

INSERT INTO CLIENTE VALUES (NULL, 'JOAO','49990650888','JOAO@IG.COM', 'MASCULINO'); 
INSERT INTO CLIENTE VALUES (NULL, 'CARLOS','5123647892','CARLOS@IG.COM', 'MASCULINO'); 
INSERT INTO CLIENTE VALUES (NULL, 'ANA','32655687413','ANA@IG.COM', 'FEMININO'); 
INSERT INTO CLIENTE VALUES (NULL, 'CLARA','265987462546',NULL, 'FEMININO'); 
INSERT INTO CLIENTE VALUES (NULL, 'JORGE','23015697456','JORGE@IG.COM', 'MASCULINO'); 
INSERT INTO CLIENTE VALUES (NULL, 'CELIA','98653214789','CELIA@IG.COM', 'FEMININO');
INSERT INTO CLIENTE VALUES (NULL, 'PAULA', '77437493', NULL, 'FEMININO'); 
INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','498795978','FLAVIO@IG.COM','Masculino');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','456231894','ANDRE@GLOBO.COM','Masculino');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','632589423',NULL,'feminino');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','785964236','KARLA@GMAIL.COM','Masculino');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','1236589452','DANIELE@GMAIL.COM','Masculino');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','4562315326',NULL,'Masculino');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','7895632456',NULL,'Masculino');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','8965234789','ANTONIO@IG.COM','Masculino');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','1236589562','ANTONIO@UOL.COM','Masculino');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','42365894123','ELAINE@GLOBO.COM','Masculino');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','1258745896','CARMEM@IG.COM','Masculino');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','2136547895','ADRIANA@GMAIL.COM','feminino');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','4569852365','JOICE@GMAIL.COM','feminino');

/* INSERINDO DADOS NA TABELA ENDERECO */ 

INSERT INTO ENDERECO VALUES (NULL, 'RUA ANTONIO SA', 'CENTRO', 'BELO HORIZONTE', 'MG', 4); 
INSERT INTO ENDERECO VALUES (NULL, 'RUA CAPITAO HERMES', 'CENTRO', 'RIO DE JANEIRO', 'RJ', 1);
INSERT INTO ENDERECO VALUES (NULL, 'RUA PRES VARGAS', 'JARDINS', 'SAO PAULO', 'SP', 3);
INSERT INTO ENDERECO VALUES (NULL, 'RUA ALFANDEGA', 'ESTACIO', 'RIO DE JANEIRO', 'RJ', 2);		
INSERT INTO ENDERECO VALUES (NULL, 'RUA DO OUVIDOR', 'FLAMENGO', 'RIO DE JANEIRO', 'RJ', 6);
INSERT INTO ENDERECO VALUES (NULL, 'RUA URUGUAIANA', 'CENTRO', 'VITORIA', 'ES', 5);
INSERT INTO ENDERECO VALUES (NULL, 'RUA OAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 7) 
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21); 

/* INSERINDO DADOS NA TABELA TELEFONE */ 

INSERT INTO TELEFONE VALUES (NULL, '952445081', 'CELULAR', 5); 
INSERT INTO TELEFONE VALUES (NULL, '965191791', 'RESIDENCIAL', 5); 
INSERT INTO TELEFONE VALUES (NULL, '998963597', 'CELULAR', 1); 
INSERT INTO TELEFONE VALUES (NULL, '961648444', 'COMERCIAL', 2); 
INSERT INTO TELEFONE VALUES (NULL, '94+974844', 'RESIDENCIAL', 1); 
INSERT INTO TELEFONE VALUES (NULL, '998935187', 'CELULAR', 3); 
INSERT INTO TELEFONE VALUES (NULL, '997984984', 'CELULAR', 3); 
INSERT INTO TELEFONE VALUES (NULL, '934849865', 'COMERCIAL', 1); 
INSERT INTO TELEFONE VALUES (NULL, '926613548', 'RESIDENCIAL', 5); 
INSERT INTO TELEFONE VALUES (NULL, '997984666', 'CELULAR', 2); 
INSERT INTO TELEFONE VALUES(NULL,'68976565','COMERCIAL',9);
INSERT INTO TELEFONE VALUES(NULL,'99656675','CELULAR',9);
INSERT INTO TELEFONE VALUES(NULL,'33567765','CELULAR',11);
INSERT INTO TELEFONE VALUES(NULL,'88668786','CELULAR',11);
INSERT INTO TELEFONE VALUES(NULL,'55689654','COMERCIAL',11);
INSERT INTO TELEFONE VALUES(NULL,'88687979','COMERCIAL',12);
INSERT INTO TELEFONE VALUES(NULL,'88965676','COMERCIAL',13);
INSERT INTO TELEFONE VALUES(NULL,'89966809','CELULAR',15);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'88679978','CELULAR',17);
INSERT INTO TELEFONE VALUES(NULL,'9955665','RESIDENCIAL',18);
INSERT INTO TELEFONE VALUES(NULL,'77455786','RESIDENCIAL',19);
INSERT INTO TELEFONE VALUES(NULL,'89766554','RESIDENCIAL',19);
INSERT INTO TELEFONE VALUES(NULL,'77755785','RESIDENCIAL',20);
INSERT INTO TELEFONE VALUES(NULL,'44522578','COMERCIAL',20);

/* RELATÓRIO GERAL DE TODOS OS CLIENTES */ 
TABELA CLIENTES: 
DESC CLIENTE
IDCLIENTE / NOME / CPF / EMAIL / SEXO / 

TABELA ENDERECO: 
DESC ENDERECO
IDENDERECO / RUA / BAIRRO / CIDADE / ESTADO / ID_CLIENTE / 

TABELA TELEFONE
DESC TELEFONE;  
IDTELEFONE / NUMERO / TIPOS / ID_CLIENTE

SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, CLIENTE.CPF, CLIENTE.EMAIL, CLIENTE.SEXO, 
       ENDERECO.RUA, ENDERECO.BAIRRO, ENDERECO.CIDADE, ENDERECO.ESTADDO, 
	   TELEFONE.NUMERO, TELEFONE.TIPOS 
FROM CLIENTE
INNER JOIN ENDERECO 
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE 
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;


/* RELATÓRIO DE HOMENS */
SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, CLIENTE.CPF, CLIENTE.EMAIL, CLIENTE.SEXO, ENDERECO.RUA, ENDERECO.BAIRRO, ENDERECO.CIDADE, ENDERECO.ESTADDO, TELEFONE.NUMERO, TELEFONE.TIPOS 
FROM CLIENTE
INNER JOIN ENDERECO 
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE 
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE SEXO = 'MASCULINO';

/* ATUALIZANDO OS CADASTROS ERRADOS */ 
UPDATE CLIENTE 
SET SEXO = 'FEMININO'
WHERE IDCLIENTE IN (11, 12, 13, 17, 18);


/* RELATÓRIO DE MULHERES */
SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, CLIENTE.CPF, CLIENTE.EMAIL, CLIENTE.SEXO, ENDERECO.RUA, ENDERECO.BAIRRO, ENDERECO.CIDADE, ENDERECO.ESTADDO, TELEFONE.NUMERO, TELEFONE.TIPOS 
FROM CLIENTE
INNER JOIN ENDERECO 
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE 
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE SEXO = 'FEMININO';

/* QUANTIDADE DE HOMENS E MULHERES */
SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO; 

/* IDS E EMAILS DAS MULHERES QUE MORAM NO CENTRO DO RIO DE JANEIRO E NÃO TENHAM CELULAR */
SELECT C.IDCLIENTE, C.EMAIL
FROM CLIENTE C
INNER JOIN ENDERECO E 
    ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T 
    ON C.IDCLIENTE = T.ID_CLIENTE
    AND T.TIPOS = 'CELULAR'
WHERE E.BAIRRO = 'CENTRO'
  AND E.ESTADDO = 'RJ'
  AND C.SEXO = 'FEMININO'
  AND T.IDTELEFONE IS NULL;

/* PARA UMA CAMPANHA DE MARKETING , O SETOR SOLICITOU UM RELATÓRIO COM O NOME, EMAIL 
   E TELEFONE CELULAR DO CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO VOCÊ TERÁ 
   QUE PASSAR  A QUERY PARA GERAR O RELATOIRIO PARA O PROGRAMADOR */ 
   
 SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR  /* PROJEÇÃO */ 
 FROM CLIENTE C /* ORIGEM */  
 INNER JOIN ENDERECO E /* JUNÇÃO */ 
 ON C.IDCLIENTE = E.ID_CLIENTE /* CONDIÇÃO DA JUNÇÃO */
 INNER JOIN TELEFONE T /* JUNÇÃO */ 
 ON C.IDCLIENTE = T.ID_CLIENTE /* CONDIÇÃO DA JUNÇÃO */
 WHERE ESTADDO = 'RJ' AND TIPOS = 'CELULAR'; /* SELEÇÃO */
 
/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM 
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSRA A QUERY PARA GERAR O RELATORIO PARA O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR 
FROM CLIENTE C
INNER JOIN ENDERECO E  
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'FEMININO'
AND E.ESTADDO = 'SP'
AND T.TIPOS = 'CELUELAR';
 