/* SISTEMA DE BANCO DE DADOS DE UM COMÉRCIO */ 
/* O NOME DO COMERCIO VAI SER LOPES */

/* CRIANDO O BANCO */ 
CREATE DATABASE LOPES;

/* CONECTANDO-SE AO BANCO */ 
USE LOPES; 

/* CRIANDO TABELAS */ 

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,  /* CHAVE PRIMÁRIA */
	NOME VARCHAR(50) NOT NULL, 
	EMAIL VARCHAR(100), 
	SEXO ENUM ('M','F') NOT NULL,
	DATACADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP /* DATA DO REGISTRO */ 
);

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT, 
	RUA VARCHAR(50) NOT NULL, 
	CIDADE VARCHAR(50) NOT NULL, 
	ESTADO CHAR(2) NOT NULL, 
	ID_CLIENTE INT UNIQUE, /* CHAVE ESTRANGEIRA E O UNIQUE FAZ COM QUE NÃO SEJA PERMITIDO UM DADO IGUAL */ 
	
	FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT, 
	NUMERO VARCHAR(15) NOT NULL, 
	TIPO ENUM('CEL','COM','RES') NOT NULL, 
	ID_CLIENTE INT, 
	
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
	
);

CREATE TABLE VENDEDOR (
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT, 
	NOME VARCHAR(50) NOT NULL, 
	VALOR_VENDAS_JANEIRO FLOAT(10,2) NOT NULL, 
	VALOR_VENDAS_FEVEREIRO FLOAT(10,2) NOT NULL, 
	VALOR_VENDAS_MARCO FLOAT(10,2) NOT NULL 
);

/* CRIANDO OS INSERTS E DIVIDINDO POR TABELAS */ 

/* TABELA CLIENTE */ 
INSERT INTO CLIENTE VALUES (NULL, 'MATHEUS FÉLIX', 'MATHEUS.FELIX2205@GMAIL.COM', 'M');
INSERT INTO CLIENTE VALUES (NULL, 'CAROL XAVIER', 'CAROL.XAVIER@GMAIL.COM', 'F');
INSERT INTO CLIENTE VALUES (NULL, 'MAYTHE FÉLIX', 'MAYTHE.FELIX1705@GMAIL.COM', 'F');
INSERT INTO CLIENTE VALUES (NULL, 'EDSON FÉLIX', 'EDSON.FELIX0605@GMAIL.COM', 'M');
INSERT INTO CLIENTE VALUES (NULL, 'EDNEIA RODRIGUES', 'EDNEIA.RODRIGUES1806@GMAIL.COM', 'F');
INSERT INTO CLIENTE (NOME, EMAIL, SEXO) VALUES
('ANA PAULA SILVA', 'ana.silva@gmail.com', 'F'),
('BRUNO HENRIQUE', NULL, 'M'),
('CARLA MENDES', 'carla.mendes@gmail.com', 'F'),
('DANIEL SOUZA', 'daniel.souza@gmail.com', 'M'),
('ELISA PEREIRA', NULL, 'F'),
('FELIPE ROCHA', 'felipe.rocha@gmail.com', 'M'),
('GABRIELA COSTA', 'gabriela.costa@gmail.com', 'F'),
('HENRIQUE LIMA', NULL, 'M'),
('ISABELA ALVES', 'isabela.alves@gmail.com', 'F'),
('JOÃO VITOR', 'joao.vitor@gmail.com', 'M'),
('KARINA FREITAS', NULL, 'F'),
('LUCAS MARTINS', 'lucas.martins@gmail.com', 'M'),
('MARIANA RIBEIRO', 'mariana.ribeiro@gmail.com', 'F'),
('NATHAN OLIVEIRA', NULL, 'M'),
('PAULA TEIXEIRA', 'paula.teixeira@gmail.com', 'F');

/* TABELA ENDERECO */ 
INSERT INTO ENDERECO VALUES (NULL, 'TRAVESSA CARMEM MIRANDA', 'SANTO ANDRÉ', 'SP', 1);
INSERT INTO ENDERECO VALUES (NULL, 'AVENIDA JOÃO PESSOA', 'SANTO ANDRÉ', 'SP', 2);
INSERT INTO ENDERECO VALUES (NULL, 'RUA EUSTÁCIO DE MELO', 'SÃO JOSÉ DO RIO PRETO', 'SP', 3);
INSERT INTO ENDERECO VALUES (NULL, 'RUA NEW YORK', 'PRAIA GRANDE', 'SP', 4);
INSERT INTO ENDERECO VALUES (NULL, 'RUA MARIO COSTA', 'RIO DE JANEIRO', 'RJ', 5);
INSERT INTO ENDERECO (RUA, CIDADE, ESTADO, ID_CLIENTE) VALUES
('Rua das Flores', 'São Paulo', 'SP', 6),
('Av. Brasil', 'Rio de Janeiro', 'RJ', 7),
('Rua Afonso Pena', 'Belo Horizonte', 'MG', 8),
('Rua XV de Novembro', 'Curitiba', 'PR', 9),
('Rua Central', 'Campinas', 'SP', 10),
('Av. Paulista', 'São Paulo', 'SP', 11),
('Rua das Palmeiras', 'Santos', 'SP', 12),
('Rua Bahia', 'Salvador', 'BA', 13),
('Av. Atlântica', 'Rio de Janeiro', 'RJ', 14),
('Rua Goiás', 'Goiânia', 'GO', 15),
('Rua Pernambuco', 'Recife', 'PE', 16),
('Av. Independência', 'Porto Alegre', 'RS', 17),
('Rua Amazonas', 'Manaus', 'AM', 18),
('Rua Ceará', 'Fortaleza', 'CE', 19),
('Av. das Nações', 'Brasília', 'DF', 20);


/* TABELA TELEFONE */ 
INSERT INTO TELEFONE VALUES (NULL, '(11)95244-5081','CEL',1);
INSERT INTO TELEFONE VALUES (NULL, '(11)4997-6744','RES',1);
INSERT INTO TELEFONE VALUES (NULL, '(11)98393-6290','CEL',4);
INSERT INTO TELEFONE VALUES (NULL, '(11)94888-3917','COM',5);
INSERT INTO TELEFONE (NUMERO, TIPO, ID_CLIENTE) VALUES
('(11)99999-1111', 'CEL', 6),
('(21)98888-2222', 'CEL', 7),
('(31)97777-3333', 'RES', 8),
('(41)96666-4444', 'CEL', 9),
('(11)95555-5555', 'COM', 11),
('(13)94444-6666', 'CEL', 12),
('(62)93333-7777', 'CEL', 15),
('(51)92222-8888', 'RES', 17),
('(92)91111-9999', 'CEL', 18),
('(61)90000-0000', 'COM', 20);

/* TABELA VENDEDOR */ 
INSERT INTO VENDEDOR VALUES (NULL, 'RODRIGO SERIGATTI', 10.500, 5.750, 2.320);
INSERT INTO VENDEDOR VALUES (NULL, 'JOÃO PEDRO', 11.750, 1.220, 3.987);
INSERT INTO VENDEDOR VALUES (NULL, 'MONIQUE SERIGATTI', 22.990, 10.570, 6.720);

/* 🔹 EXERCÍCIO 01 — INNER JOIN + IFNULL
OBJETIVO -> GERAR UM RELATÓRIO COM: NOME DO CLIENTE, EMAIL, CIDADE, ESTADO, NÚMERO E TIPO DE TELEFONE. 
REGRAS: USAR INNER JOIN, USAR IFNULL E ORDENAR PELO NOME.  
   📌 CONCEITOS AVALIADOS: 
INNER JOIN, IFNULL, ORDER BY */ 

SELECT C.NOME, IFNULL(C.EMAIL, 'SEM EMAIL') AS EMAIL, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C
INNER JOIN ENDERECO E  
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY C.NOME;

/* 🔹 EXERCÍCIO 02 — LEFT JOIN (clientes sem telefone)
OBJETIVO -> LISTAR TODOS OS CLIENTES QUE NÃO POSSUEM TELEFONE CADASTRADOS, EXIBINDO: 
NOME, EMAIL(TRATADO COM IFNULL).
REGRAS: USAR LEFT JOIN, FILTRAR CORRATAMENTE CLIENTES SEM TELEFONE, NÃO USAR SUBQUERY
   📌 Conceitos avaliados:
LEFT JOIN, IS NULL, IFNULL */ 

SELECT C.NOME, IFNULL(C.EMAIL, 'SEM EMAIL') AS EMAIL 
FROM CLIENTE C
LEFT JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE T.ID_CLIENTE IS NULL;

/* 🔹 EXERCÍCIO 03 — JOIN + FILTRO COMPOSTO
OBJETIVO -> LISTAR: NOME, EMAIL, CIDADE, ESTADO APENAS DE: 
CLIENTES DO SEXO FEMININO, QUE MORAM NO ESTADO DE SÃO PAULO.
   📌 Conceitos avaliados:
INNER JOIN, WHERE, filtros múltiplos */ 

SELECT C.NOME, C.EMAIL, E.CIDADE, E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE C.SEXO = 'F' AND E.ESTADO = 'SP'; 

/* 🔹 EXERCÍCIO 04 — VIEW (relatório geral)
OBJETIVO -> CRIAR UMA VIEW CHAMADA V_RELATORIO_CLIENTES CONTENDO: 
SEXO, EMAIL(TRATADO), CIDADE, ESTADO, NUMERO DE TELEFONE E TIPO. 
REGRAS: USAR JOINS, IFNULL E A VIEW DEVE FACILITAR CONSULTAS FUTURAS.
Depois: Consultar a VIEW ordenando pelo nome
   📌 Conceitos avaliados:
VIEW, JOIN, IFNULL, ORDER BY */

CREATE VIEW V_RELATORIOS_CLIENTES AS
SELECT C.NOME, C.SEXO, IFNULL(C.EMAIL, 'SEM EMAIL') AS EMAIL, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT * 
FROM V_RELATORIOS_CLIENTES
ORDER BY NOME;

/* 🔹 EXERCÍCIO 05 — GROUP BY + COUNT
OBJETIVO -> GERAR UM RELATÓRIO MOSTRANDO: SEXO, QUANTIDADE DE CLIENTES POR SEXO
   📌 Conceitos avaliados:
GROUP BY, COUNT
*/ 

SELECT SEXO, COUNT(*) AS Total
FROM CLIENTE
GROUP BY SEXO; 

/* 🔹 EXERCÍCIO 06 — FUNÇÕES DE AGREGAÇÃO (VENDEDOR)
OBJETIVO -> A PARTIR DA TABELA VENDEDOR, CRIAR CONSULTAS QUE RETORNEM: 
- MAIOR VALOR DE VENDAS EM JANEIRO; 
- MENOR VALOR DE VENDAS EM FEVEREIRO; 
- MEDIA DE VENDAS EM MARÇO (COM DUAS CASAS DECIAMAIS);
- TOTAL DE VENDAS EM JANEIRO. 
   📌 Conceitos avaliados:
MAX, MIN, AVG, TRUNCATE, SUM */ 

SELECT NOME, VALOR_VENDAS_JANEIRO 
FROM VENDEDOR 
WHERE VALOR_VENDAS_JANEIRO = (SELECT MAX(VALOR_VENDAS_JANEIRO) FROM VENDEDOR);

SELECT NOME, VALOR_VENDAS_FEVEREIRO
FROM VENDEDOR 
WHERE VALOR_VENDAS_FEVEREIRO = (SELECT  MIN(VALOR_VENDAS_FEVEREIRO) FROM VENDEDOR);

SELECT TRUNCATE(AVG(VALOR_VENDAS_MARCO),2) as media 
FROM VENDEDOR;

SELECT SUM(VALOR_VENDAS_JANEIRO) AS 'TOTAL EM JANEIRO' 
FROM VENDEDOR ;

/* 🔹 EXERCÍCIO 07 — GROUP BY + SUM
OBJETIVO -> GERAR UM RELATÓRIO COM: NOME DO VENDEDOR, TOTAL VENDIDO SOMANDO JANEIRO, FEVEREIRO E MARÇO.
   📌 Conceitos avaliados:
Operações em linha, SUM, projeção de colunas */ 

SELECT NOME, (VALOR_VENDAS_JANEIRO + VALOR_VENDAS_FEVEREIRO + VALOR_VENDAS_MARCO) AS 'TOTAL_VENDIDO'
FROM VENDEDOR;

/* 🔹 EXERCÍCIO 08 — SUBQUERY (comparação)
OBJETIVO -> LISTAR: NOME DO VENDEDOR, VALOR DE VENDAS DE FEVEREIRO, 
APENAS DO VENDEDORES QUE VENDERAM ACIMA DA MÉDA DE FEVEREIRO.
   📌 Conceitos avaliados:
SUBQUERY, AVG */ 

SELECT NOME, VALOR_VENDAS_FEVEREIRO 
FROM VENDEDOR
WHERE  VALOR_VENDAS_FEVEREIRO > (SELECT AVG(VALOR_VENDAS_FEVEREIRO) FROM VENDEDOR);

/* 🔹 EXERCÍCIO 09 — SUBQUERY (máximo e mínimo)
OBJETIVO -> CRIAR DUAS CONSULTAS: VENDEDOR QUE TEVE A MAIOR VENDA EM FEVEREIRO, VENDEDOR QUE TEVE A MENOR VENDA EM FEVEREIRO.
   📌 Conceitos avaliados:
SUBQUERY, MAX, MIN */ 

SELECT NOME, VALOR_VENDAS_FEVEREIRO
FROM VENDEDOR 
WHERE VALOR_VENDAS_FEVEREIRO = (SELECT MAX(VALOR_VENDAS_FEVEREIRO) FROM VENDEDOR);

SELECT NOME, VALOR_VENDAS_FEVEREIRO
FROM VENDEDOR 
WHERE VALOR_VENDAS_FEVEREIRO = (SELECT MIN(VALOR_VENDAS_FEVEREIRO) FROM VENDEDOR);

/* 🔹 EXERCÍCIO 10 — PROCEDURE COM PARÂMETRO
OBJETIVO -> CRIARR UMA STORED PROCEDURE CHAMADA CONSULTA_CLIENTE QUE RECEBA: 
ID DO CLIENTE COMO PARÂMETRO E RETORNE: NOME, EMAIL, CIDADE, ESTADO. 
REGRAS: USAR DELIMIER E USAR JOIN DENTRO DO PROCEDURE.
   📌 Conceitos avaliados:
PROCEDURE, DELIMITER, parâmetros */ 

DELIMITER $ 

CREATE PROCEDURE CONSULTA_CLIENTE (P_ID_CLIENTE INT)
BEGIN 
	SELECT C.NOME, C.EMAIL, E.CIDADE, E.ESTADO
	FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE= E.ID_CLIENTE
	WHERE C.IDCLIENTE = P_ID_CLIENTE;
END $

DELIMITER ; 

/* 🔹 EXERCÍCIO 11 — PROCEDURE DE RELATÓRIO
OBJETIVO -> CRIAR UMA PROCEDURE QUE GERE UMA RELATÓRIO CONTENDO: SEXO E QUANTIDADE DE CLIENTE POR SEXO.
   📌 Conceitos avaliados:
PROCEDURE, GROUP BY*/ 

DELIMITER $ 

CREATE PROCEDURE RELATORIO_SEXO()
BEGIN 
	SELECT SEXO, COUNT(*) AS TOTAL
	FROM CLIENTE 
	GROUP BY SEXO;
END 

DELIMITER ; 

/* 🔹 EXERCÍCIO 12 — ORDER BY AVANÇADO
OBJETIVO -> LISTAR TODOS OS CLIENTES ORDENADOS: PRIMEIRO POR ESTADO E DEPOIS POR NOME.
   📌 Conceitos avaliados:
ORDER BY com múltiplas colunas */ 

SELECT C.NOME, E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY E.ESTADO, C.NOME;







